### ISSUE TITLE
Определить политику использования Issue

### ISSUE THREAD

**Issue by sevryukov** [RisaMagpie/Data-Analysis#1]
Выявить вопросы по использованию Issue в проекте. В последующем на основе ответов сформировать политику (порядок использования) Issue в проекте.

**Comment by HollowPrincess** [comment]
Может помимо тегов и milestones есть смысл связать Issues и to-do листы во вкладке [Projects](https://github.com/RisaMagpie/Data-Analysis/projects)?

**Comment by sevryukov** [comment]
Может и есть смысл - почему бы не попробовать?

**Comment by HollowPrincess** [comment]
Milestones являются тематическими блоками работы, которые могут быть раскиданы по времени, или являются блоками-итерациями работы над проектом?

**Comment by sevryukov** [comment]
> 

> Milestones являются тематическими блоками работы, которые могут быть раскиданы по времени, или являются блоками-итерациями работы над проектом?

Ну это как Вы решите и что для Вас будет удобнее.

**Comment by sevryukov** [comment]
В #7 и #10 Вы используете подмножество в виде чек-листа. Это допустимо, но обременено следующими проблемами:
- Список может меняться (добавляться новые элементы, изменяться уже существующие)
- Тяжело оценить объём работы
- Тяжело фиксировать фидбек (комментарии) по отдельной составляющей или отделять комментарии по отдельной составляющей
- Тяжело или невозможно менять исполнителей для отдельной составляющей (в случае командной работы).

В случае заведения Issue для каждой отдельной составляющей лишь увеличивается объём работы по оформлению общей части (например, тегов или чек-листа). Общую часть можно зафиксировать в шаблоне Issue, что смягчает это обременение.

**Comment by HollowPrincess** [comment]
@sevryukov хорошо, я приняла во внимание, сейчас оформлю эти issue в отдельные, чтобы было удобнее писать фидбеки.

**Comment by HollowPrincess** [comment]
В заданиях, связанных с обзором статей/методов/инструментов и тд, ссылки на объекты обзора и отчеты стоит хранить в облаке и под issue прикреплять ссылки или хранить в вики проекта или сделать папку в репозитории?

**Comment by HollowPrincess** [comment]
В [проекте](https://github.com/RisaMagpie/Data-Analysis/projects/4) я добавила столбец "Необходима проверка" - туда будут направляться выполненные issue, на которые я хочу чтобы Вы обратили внимание
