### ISSUE TITLE
Сравнение СУБД

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#10]
Здесь будут аккумулироваться полезные ссылки на тему выбора СУБД

**Comment by HollowPrincess** [comment]
https://github.com/RisaMagpie/Data-Analysis/issues/17 https://github.com/RisaMagpie/Data-Analysis/issues/18 https://github.com/RisaMagpie/Data-Analysis/issues/19 https://github.com/RisaMagpie/Data-Analysis/issues/20

**Comment by HollowPrincess** [comment]
Примерный алгоритм выбора СУБД:

1. Ознакомиться с литературой
2. Выбрать критерии сравнения
3. Выбрать конкурсантов
4. Выбрать методику тестирования
5. Провести тестирование
6. Провести анализ результатов
7. Оформить отчет 
8. Предложить рекомендации 
Источник: https://habr.com/ru/company/oleg-bunin/blog/329062/

**Comment by HollowPrincess** [comment]
Рейтинг СУБД:
https://db-engines.com/en/ranking

**Comment by HollowPrincess** [comment]
Инструмент от Oracle для сравнения баз: https://docs.oracle.com/database/121/ARPLS/d_comparison.htm#ARPLS868 

сравнивает именно базы, а не субд

**Comment by HollowPrincess** [comment]
Сравнение Nosql in-memory http://highscalability.com/blog/2015/12/30/how-to-choose-an-in-memory-nosql-solution-performance-measur.html

**Comment by HollowPrincess** [comment]
https://en.wikipedia.org/wiki/YCSB
не сравнивает нужные нам СУБД

**Comment by HollowPrincess** [comment]
Внимательно посмотреть этот список: https://habr.com/ru/company/tinkoff/blog/310620/

**Comment by HollowPrincess** [comment]
https://segment.com/docs/guides/warehouses/how-do-i-decide-between-redshift-postgres-and-bigquery/

**Comment by HollowPrincess** [comment]
Сравнение Exasol с Oracle: https://habr.com/ru/post/318416/

**Comment by RisaMagpie** [comment]
Сравнение Exasol с Oracle: https://habr.com/ru/post/318416/

**Comment by HollowPrincess** [comment]
https://habr.com/ru/post/319902/ 
http://www.tpc.org/tpch/

**Comment by HollowPrincess** [comment]
Инструмент: http://www.tpc.org/tpch/ 
Пример: https://sohabr.net/habr/post/319902/ 
Коротко о спецификации: https://www.exasol.com/en/blog/10-questions-about-the-tpc-h-benchmark/ 
Еще пример: http://savepearlharbor.com/?p=282617
