### ISSUE TITLE
Загрузить логи в базу

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#105]

**Comment by HollowPrincess** [comment]
https://medium.com/nuances-of-programming/начало-работы-с-elasticsearch-в-python-часть-1-73d6aa6be215

**Comment by HollowPrincess** [comment]
https://medium.com/nuances-of-programming/начало-работы-с-elasticsearch-в-python-часть-2-412796dcb213

**Comment by HollowPrincess** [comment]
https://nuancesprog.ru/p/1818/

**Comment by HollowPrincess** [comment]
https://habr.com/ru/post/280488/

**Comment by HollowPrincess** [comment]
https://ruseller.com/lessons.php?rub=37&id=2409

**Comment by HollowPrincess** [comment]
https://mkdev.me/posts/vvedenie-v-elk-sobiraem-filtruem-i-analiziruem-bolshie-dannye

**Comment by HollowPrincess** [comment]
Про json: http://qaru.site/questions/108532/importindex-a-json-file-into-elasticsearch

**Comment by HollowPrincess** [comment]
На python: http://carrefax.com/new-blog/2018/3/12/load-json-files-into-elasticsearch

**Comment by HollowPrincess** [comment]
Documentation: https://www.elastic.co/guide/index.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html

**Comment by RisaMagpie** [comment]
Documentation: https://www.elastic.co/guide/index.html

**Comment by HollowPrincess** [comment]
Mapping: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by HollowPrincess** [comment]
https://tryolabs.com/blog/2015/02/17/python-elasticsearch-first-steps/

**Comment by HollowPrincess** [comment]
http://qaru.site/questions/6634367/upload-json-file-to-elastic-search-using-python

**Comment by HollowPrincess** [comment]
https://elasticsearch-py.readthedocs.io/en/master/

**Comment by HollowPrincess** [comment]
https://docs.objectrocket.com/elastic_python_examples.html

**Comment by HollowPrincess** [comment]
https://www.youtube.com/watch?v=s2U9mAnqH50

**Comment by HollowPrincess** [comment]
https://www.logicalfeed.com/posts/1182/upload-bulk-json-data-to-elasticsearch-using-python
https://discuss.elastic.co/t/import-json-through-python/113766
https://stackoverflow.com/questions/43981275/index-json-files-in-elasticsearch-using-python

**Comment by HollowPrincess** [comment]
JSON файл должен соответствовать bulk формату, а именно:
{ "index": {"_index": "my_index", "_type":"mytype","_id":"my_id1"} }
{1 документ-объект json}
{ "index": {"_index": "my_index", "_type":"mytype","_id":"my_id2"} }
{2 документ-объект json}
...

**Comment by HollowPrincess** [comment]
Для того, чтобы написать файл, подходящий под Bulk установила jq

**Comment by HollowPrincess** [comment]
Создание файла с индексом по-умолчанию:
jq-win64 -c  ". | {"index": {}}, ." spbutest0.json > bulk.json

По-умолчанию индекс mydb
тип _doc
id случайный

**Comment by HollowPrincess** [comment]
Создание базы:
curl -H "Content-Type: application/json" -XPOST "localhost:9200/mydb/_doc/_bulk?pretty&refresh" --data-binary "@bulk.json"

**Comment by HollowPrincess** [comment]
Посмотреть индексы:
curl "localhost:9200/_cat/indices?v"

**Comment by HollowPrincess** [comment]
Удалить индекс:
curl -X DELETE "localhost:9200/имя_индекса"

**Comment by HollowPrincess** [comment]
Ход работы:
https://docs.google.com/document/d/1JGJz8bHL_RGRy7Glf4Gqc7yCwRxJ1-sJplIeUYURWn4/edit#
