### ISSUE TITLE
Посчитать средние оценки, отсортировать и вывести сравнение. 

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#112]
Для полей с оценками вычислить среднее, построить один общий график для всех курсов.
Отметить нерепрезентативные данные.

**Comment by HollowPrincess** [comment]
https://docs.google.com/document/d/1sQvh2WoiEwaxu-R8b99qp9VLJ0XmhomDOa6FBS1bU5o/edit

**Comment by RisaMagpie** [comment]
https://docs.google.com/document/d/1sQvh2WoiEwaxu-R8b99qp9VLJ0XmhomDOa6FBS1bU5o/edit
