### ISSUE TITLE
Попробовать plotly или dash

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#119]
https://plot.ly/products/dash/

**Comment by HollowPrincess** [comment]
https://plot.ly/python/ipython-notebook-tutorial/

**Comment by HollowPrincess** [comment]
https://plot.ly/python/bar-charts/

**Comment by RisaMagpie** [comment]
Aw, snap! We didn't get a username with your request.

Don't have an account? https://plot.ly/api_signup

Questions? accounts@plot.ly

**Comment by HollowPrincess** [comment]
https://plot.ly/python/getting-started/#initialization-for-online-plotting

**Comment by HollowPrincess** [comment]
plotly делает только публичные графики без подписки

**Comment by HollowPrincess** [comment]
Dash делает графики через plotly и создает веб страницы. При этом графики не сохраняются в аккаунте plotly.
