### ISSUE TITLE
Создать Issue на основе обсуждений 19.10.2018

### ISSUE THREAD

**Issue by sevryukov** [RisaMagpie/Data-Analysis#3]

**Comment by HollowPrincess** [comment]
https://github.com/RisaMagpie/Data-Analysis/issues/4   https://github.com/RisaMagpie/Data-Analysis/issues/5   https://github.com/RisaMagpie/Data-Analysis/issues/6 
После анализа статей думаю есть необходимость сформулировать issues, связанные с обзором методов анализа, СУБД и средств визуализации данных.

**Comment by sevryukov** [comment]
В письме Вы написали: "часть я не записала, потому что пока нет представления о четкой поставновке задачи".
Так может оформить несколько Issue с открытыми вопросами и цитатами фрагментов, которые требуют уточнений?

**Comment by sevryukov** [comment]
В обсуждениях прозвучала информация о различных сервисах и на встрече некоторые из них Вам стали известны впервые. Нет ли смысла оформить задачи по ознакомлению с ними?

**Comment by HollowPrincess** [comment]
Задачи по ознакомлению и поиску: https://github.com/RisaMagpie/Data-Analysis/issues/9 https://github.com/RisaMagpie/Data-Analysis/issues/10 https://github.com/RisaMagpie/Data-Analysis/issues/11

**Comment by HollowPrincess** [comment]
@sevryukov, сейчас вроде все issue добавлены

**Comment by sevryukov** [comment]
Согласен
