### ISSUE TITLE
Создать check list для чтения статей

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#4]
В списке написать моменты, которые стоит выделить при прочтении.

**Comment by HollowPrincess** [comment]
Возможный [CheckList](https://docs.google.com/document/d/1koRW0_6nmwOlDpzcYcGFx6PCQ1LEdf2E9H5yBDxG7UU/edit)

**Comment by sevryukov** [comment]
@RisaMagpie Проверил, согласую.
