### ISSUE TITLE
Обзор литературы

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#5]
### Прочитать 10+ статей по анализу данных и по анализу данных онлайн курсов.
***
Написать краткие **отчёты** и отметить все моменты, которые занесены в **check list для статей** https://github.com/RisaMagpie/Data-Analysis/issues/4 .
***
**Поиск статей** можно осуществлять при помощи списка литературы: поиск предшествующих статей(предков) и статей, которые ссылаются на предка(потомки), есть вероятность, что потомки будут похожи на статью, которая являлась отправной точкой поиска.
***
**Полезные сервисы**:
- google scalar (google Академия) - сервис поиска
- research gate - соцсеть для обмена научными знаниями (полезно искать связи межу статьями, сообщества, соответствующие тематике работы)
- Springer - каталог статей с функцией поиска (доступ закрыт, доступен для spbu)
- Dspace

**Comment by sevryukov** [comment]
"Долгоиграющие" задачи не мотивируют к выполнению.
Более того, если есть задача "прочитать статьи", значит уже решена задача "найти статьи". А если решена задача "найти статьи", то уже решена задача "ознакомиться с такими-то средствами поиска".
Это я поделился мнением, не настаиваю на чём-либо.

**Comment by HollowPrincess** [comment]
Дробление: https://github.com/RisaMagpie/Data-Analysis/issues/7 https://github.com/RisaMagpie/Data-Analysis/issues/8
