### ISSUE TITLE
Установить СУБД и вычислить производительность на запросах и загрузке данных

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#95]

**Comment by sevryukov** [comment]
Это объемная и серьёзная задача. Нужна методика тестирования, тестовые сценарии и данные, средства замера, система оценки.

Если Вы сделаете более или менее объективное сравнение (которое никто не сделал до Вас), то это уже будет большой самостоятельной задачей.

**Comment by HollowPrincess** [comment]
@sevryukov  
Я думала воспользоваться вот этим инструментом для оценки производительности: http://www.tpc.org/tpch/ 
Насколько я понимаю, он включает в себя тестовые данные, запросы и средства замера.
Пример использования: https://sohabr.net/habr/post/319902/

**Comment by sevryukov** [comment]
@RisaMagpie Обсудили на встрече.
